version: '3.8'

services:
  backend:
    build: .
    container_name: flask_app
    env_file:
      - ./.env
    ports:
      - "${FLASK_OUTER_PORT}:${FLASK_INNER_PORT}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 -p ${FLASK_INNER_PORT}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${FLASK_INNER_PORT}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:latest
    container_name: flask_db
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: