version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    env_file:
      - ./.env
    ports:
      - "${FLASK_OUTER_PORT}:${FLASK_INNER_PORT}"
    depends_on:
      - db
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 -p ${FLASK_INNER_PORT}

  db:
    image: postgres:latest
    container_name: flask_db
    restart: always
    ports:
      - "${POSTGRES_OUTER_PORT}:${POSTGRES_PORT}"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: